spring:
  application:
    name: kotlinapi

  datasource:
    url: jdbc:postgresql://localhost:5432/SampleApp
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history
    schemas: public
    validate-on-migrate: true
    clean-disabled: true

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
#    default-schema: public
#    user: postgres
#    password: root


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html