# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sampleappapi:
    image: sampleappapi
    build:
      context: .
      dockerfile: SampleApp.API/Dockerfile
    ports:
      - 5299:5299
